package mx.personas.api.common.error;

import org.springframework.http.HttpStatus;

/**
 * Catalogo de codigos de error estables de la API.
 * Ver specs/001-personas-codigos-postales/contracts/error-format.md
 */
public enum ErrorCode {

    VALIDACION_FALLIDA(HttpStatus.BAD_REQUEST),
    CP_FORMATO_INVALIDO(HttpStatus.BAD_REQUEST),
    FECHA_NACIMIENTO_FUTURA(HttpStatus.BAD_REQUEST),
    COLONIA_NO_VALIDA_PARA_CP(HttpStatus.BAD_REQUEST),
    PERSONA_NO_ENCONTRADA(HttpStatus.NOT_FOUND),
    CP_NO_ENCONTRADO(HttpStatus.NOT_FOUND),
    PERSONA_CORREO_DUPLICADO(HttpStatus.CONFLICT),
    PERSONA_CURP_DUPLICADO(HttpStatus.CONFLICT),
    NO_AUTENTICADO(HttpStatus.UNAUTHORIZED),
    ACCESO_DENEGADO(HttpStatus.FORBIDDEN),
    USUARIO_LOGIN_DUPLICADO(HttpStatus.CONFLICT),
    USUARIO_NO_ENCONTRADO(HttpStatus.NOT_FOUND),
    PERSONA_YA_ACTIVA(HttpStatus.CONFLICT),
    PERSONA_CURP_ELIMINADA(HttpStatus.CONFLICT),
    CATALOGO_ARCHIVO_INVALIDO(HttpStatus.BAD_REQUEST),
    CATALOGO_ARCHIVO_DEMASIADO_GRANDE(HttpStatus.BAD_REQUEST),
    CATALOGO_IMPORTACION_EN_CURSO(HttpStatus.CONFLICT),
    PROFESION_NOMBRE_DUPLICADO(HttpStatus.CONFLICT),
    PROFESION_NOMBRE_DESACTIVADA(HttpStatus.CONFLICT),
    PROFESION_DESACTIVADA(HttpStatus.CONFLICT),
    PROFESION_NO_ENCONTRADA(HttpStatus.NOT_FOUND),
    PERSONA_PROFESION_YA_ASIGNADA(HttpStatus.CONFLICT),
    PERSONA_ELIMINADA(HttpStatus.CONFLICT),
    PERSONA_PROFESION_NO_ENCONTRADA(HttpStatus.NOT_FOUND),
    PERSONA_PROFESION_YA_RETIRADA(HttpStatus.CONFLICT),
    AUTOMOVIL_PLACAS_DUPLICADAS(HttpStatus.CONFLICT),
    AUTOMOVIL_VIN_DUPLICADO(HttpStatus.CONFLICT),
    AUTOMOVIL_NO_ENCONTRADO(HttpStatus.NOT_FOUND),
    AUTOMOVIL_ELIMINADO(HttpStatus.CONFLICT),
    AUTOMOVIL_YA_ACTIVO(HttpStatus.CONFLICT),
    MANTENIMIENTO_NO_ENCONTRADO(HttpStatus.NOT_FOUND),
    MANTENIMIENTO_YA_ACTIVO(HttpStatus.CONFLICT),
    KILOMETRAJE_INCONSISTENTE(HttpStatus.CONFLICT),
    MECANICO_NO_ENCONTRADO(HttpStatus.BAD_REQUEST),
    MECANICO_ELIMINADO(HttpStatus.CONFLICT),
    MECANICO_SIN_PROFESION_ACTIVA(HttpStatus.CONFLICT);

    private final HttpStatus httpStatus;

    ErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus getHttpStatus() {
        return httpStatus;
    }
}
